CC := /home/checked/clang-0.8/build/bin/clang

all: sample1 sample2

check: checked1

sample1: sample1.c
	$(CC) sample1.c -o s1

sample2: sample2.c
	$(CC) sample2.c -o s2

checked1: checked1.c
	$(CC) checked1.c -o c1

